### ISSUE TITLE
[8.0] project_work_time_control - Allow select done tasks

### ISSUE THREAD

**Issue by rafaelbn** [serviciosbaeza/serviciosbaeza-odoo-addons#15]
When you select a project its show you all tasks of the project. It must exclude tasks which are done or canceled

**Comment by pedrobaeza** [comment]
That it's because now there's no state on tasks, but stages, so the logic must be completely changed for covering this need.

**Comment by rafaelbn** [comment]
@pedrobaeza could you fix this issue please? This module is not useful is you get all task in all the database when selecting from this view. Let me know how to arrange this change.
Note: I would like to improve functionality -> Not to show project which the user don't belong (follower), as in the project view from the core functionality.

**Comment by rafaelbn** [comment]
@pedrobaeza any possibility to move this module to OCA?

**Comment by pedrobaeza** [comment]
Closed in https://github.com/serviciosbaeza/serviciosbaeza-odoo-addons/commit/268e19d2d99c1fd609894d77af5942baa31381eb

**Comment by rafaelbn** [comment]
Readme and **openerp**.py must be update.
But functionality is :+1:

**Comment by rafaelbn** [comment]
Hi @pedrobaeza, check this:

![2015-11-22_7-20-50](https://cloud.githubusercontent.com/assets/8736623/11322405/397b3c84-90ea-11e5-9832-65de9454198b.png)

**Comment by pedrobaeza** [comment]
This is because you haven't unchecked in the stage "Include in time control view" (or similar).
