### ISSUE TITLE
[9.0]porting module product_supplierinfo_variant

### ISSUE THREAD

**Issue by flotho** [serviciosbaeza/serviciosbaeza-odoo-addons#18]
Hi,

I would like to port your module product_supplierinfo_variant.
Is there also any chance to have a branch 9.0 or to port it in the OCA repo?
Thanks in advance for letting me Know

**Comment by pedrobaeza** [comment]
I haven't moved the module to OCA because it's not feature complete yet, but I have created the 9.0 branch in my repository if you want to proceed with the migration.

**Comment by metaminux** [comment]
Hello,

It seems commit odoo/odoo@b65c67a2598fd3ad433af05ed49d398c473b76ae implemented this feature in Odoo 9.0.

This issue should be closed so, isn't it ?
