### ISSUE TITLE
No matching record found for external id 'model_account_periodical_invoicing_agreement' in field 'Object'"

### ISSUE THREAD

**Issue by AizenL** [serviciosbaeza/serviciosbaeza-odoo-addons#23]
Odoo V8

Error while importing module 'account_periodical_invoicing': u"Module loading account_periodical_invoicing failed: file /tmp/tmpoQ2dq2/account_periodical_invoicing/security/ir.model.access.csv could not be processed:\n Line 1 : No matching record found for external id 'model_account_periodical_invoicing_agreement' in field 'Object'"

**Comment by pedrobaeza** [comment]
Version?

**Comment by AizenL** [comment]
Hi, I have tested in two versions:

Version 8.0-a2115ef (My Server)
and 
Version 8.0 (Runbot) http://125461-8-0-bd4e6f.runbot.odoo.com/web/login

**Comment by pedrobaeza** [comment]
I think you're importing the module with the wizard, and that's not valid because that's only for data modules. Use apps.

**Comment by AizenL** [comment]
HI, I only did that on the Runbot but on my server I use the traditional way via FTP, and using SSH PUTTY to move the .zip to addons folder and etc.

**Comment by pedrobaeza** [comment]
ZIP file? Maybe that's the problem. You have to put the module uncompressed (in a folder), and then click in the menu "Update module list".

**Comment by AizenL** [comment]
Hi obviously I unziped te file, thats why im getting the error. I think its related to model.access.csv

**Comment by pedrobaeza** [comment]
Then the problem should be the permissions. Module is correctly working and your problem is unrelated to the module itself, so I close the issue.
