### ISSUE TITLE
[8.0] Fallo en facturas recurrentes

### ISSUE THREAD

**Issue by syci** [serviciosbaeza/serviciosbaeza-odoo-addons#24]
Al ejecutar el cron da el siguiente error:

Traceback (most recent call last):
  File "/home/mario/odoo/OCB/openerp/addons/base/ir/ir_cron.py", line 138, in _callback
    getattr(model, method_name)(cr, uid, _args)
  File "/home/mario/odoo/OCB/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, *_kwargs)
  File "/home/mario/odoo/OCB/openerp/api.py", line 372, in old_api
    result = method(recs, _args, *_kwargs)
  File "/home/mario/odoo/serviciosbaeza-odoo-addons/account_periodical_invoicing/models/periodical_invoicing.py", line 296, in make_invoices_planned
    fields.Date.from_string(agreement.next_expiration_date))):
TypeError: can't compare datetime.date to NoneType

**Comment by colmeirin** [comment]
A mi me pasó lo mismo antes de migrar a los contratos de odoo...

Se puede replicar el error creando un agreement con:
Prolongación: Plazo ilimitado
Próxima fecha de expiración: [vacio]

Soluciones:
- Asigna una fecha de expiración a tus contratos para que no encuentre el campo vacío al hacer la comprobación...
- Migra los contratos al modelo nativo de odoo account_analytic_analysis
- Propón un cambio en https://github.com/serviciosbaeza/serviciosbaeza-odoo-addons/blob/8.0/account_periodical_invoicing/models/periodical_invoicing.py#L296 para que compruebe que el campo **next_expiration_date** existe antes de usarlo.

Un saludo!

**Comment by syci** [comment]
Bueno, en principio no eran muchos contratos y los he traspasado al modelo nativo. Ya se queda a la espera de que Pedro pueda solucionar con la comprobación del campo. Gracias.

**Comment by pedrobaeza** [comment]
La cuestión es que ese campo nunca debería estar vacío, ya que el código que lo rellena siempre pone un valor: https://github.com/serviciosbaeza/serviciosbaeza-odoo-addons/blob/8.0/account_periodical_invoicing/models/periodical_invoicing.py#L72-L94

El problema proviene de no tener un depends asociado que haga recalcular el campo.

Solucionado en https://github.com/serviciosbaeza/serviciosbaeza-odoo-addons/commit/37858903448fd17f0c51a3475383780ddcc90538
