### ISSUE TITLE
Error: "unsupported type for add operation" in account_periodical_invoicing

### ISSUE THREAD

**Issue by sschuchlenz** [serviciosbaeza/serviciosbaeza-odoo-addons#27]
I've installed and used your periodical invoicing module in other instances of odoo8 successfully, but on our new server (also odoo8 instances there) when adding a new periodical invoicing agreement, I get the following errors:

`File "/home/odoo/.local/share/Odoo/addons/8.0/account_periodical_invoicing/models/periodical_invoicing.py", line 85, in _get_next_expiration_date
    agreement.prolong_unit, agreement.prolong_interval)
  File "/home/odoo/.local/share/Odoo/addons/8.0/account_periodical_invoicing/models/periodical_invoicing.py", line 51, in _get_next_term_date
    return date + relativedelta(years=interval)
  File "/usr/local/lib/python2.7/dist-packages/dateutil/relativedelta.py", line 247, in __radd__
    raise TypeError, "unsupported type for add operation"
TypeError: unsupported type for add operation`

I added a full gist here: https://gist.github.com/sschuchlenz/3703ce1420d05efeaa1cc51e91fce667

**Comment by pedrobaeza** [comment]
You should update your relativedelta library.
