### ISSUE TITLE
Error project_task_work_print 

### ISSUE THREAD

**Issue by insideth** [serviciosbaeza/serviciosbaeza-odoo-addons#28]
Hola Pedro, acabo de actualizar a la última versión (8.0.1.1.0) y me aparece este error;

> cannot identify image file
> fileName=<cStringIO.StringI object at 0x7f616fc6e0b8> identity=[ImageReader@0x7f616dccd450]
> handle_pageBegin args=()
> 
> <type 'exceptions.IOError'>,cannot identify image file
> fileName=<cStringIO.StringI object at 0x7f616fc6e0b8> identity=[ImageReader@0x7f616dccd450]
> handle_pageBegin args=(),<traceback object at 0x7f616e648ea8>

He reiniciado Odoo y hecho el proceso de actualización del módulo project

Gracias por el estupendo módulo!

**Comment by pedrobaeza** [comment]
Eso se puede deber a la librería de procesamiento de imagen (PIL frente a pillow). Yo no tengo ninguno de esos problemas.

**Comment by insideth** [comment]
Gracias por la rápida respuesta, ¿alguna indicación para solventarlo?

**Comment by pedrobaeza** [comment]
Reinstala la librería con

```
sudo pip install pillow --upgrade
```

**Comment by insideth** [comment]
Pedro parece ser que finalmente el problema venía por una actualización de los paquetes: python-imaging  y python-pil en Ubuntu 14.04. He restaurado la instalación a un punto anterior y la versión nueva de project_task_work_print funciona correctamente. Ha dado la casualidad que he aplicado las dos actualizaciones al mismo tiempo (la del módulo y la de python), de ahí que achacara el problema al módulo (mi conocimiento de Python es prácticamente nulo).

Intenté solvertarlo con: sudo pip install pillow --upgrade, e instalando las librerías: libtiff5-dev libjpeg8-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python-tk que según un bug publicado por Pillow parece ser que son necesarias, pero no he logrado solventarlo por esta via.

Gracias por el soporte.

**Comment by pedrobaeza** [comment]
Te falta también por instalar python-dev para poder instalarlo via pip.

**Comment by insideth** [comment]
python-dev lo tenía ya instalado, y pude instalarlo via pip, pero el error persistía...

**Comment by pedrobaeza** [comment]
Reiniciando el servicio de Odoo debería salir funcionando... en cualquier caso, si ya lo tienes, pues así puede valer :wink:
