### ISSUE TITLE
[8.0] No aparecen las fechas en la columna Date

### ISSUE THREAD

**Issue by insideth** [serviciosbaeza/serviciosbaeza-odoo-addons#34]
Hola, he hecho un pull desde Github y he aplicado las últimas actulizaciones a mi instalación de Odoo 8. Desde ese momento al generar el informe de proyectos en .pdf la columna Date sale vacía.

He probado a hacer un update del plugin y continúa igual, ¿alguna sugerencia?

Gracias de antemano.

**Comment by pedrobaeza** [comment]
¿De qué módulo hablas?

**Comment by insideth** [comment]
Perdona, es sobre project_task_work_print

**Comment by pedrobaeza** [comment]
Pues no te sabría decir. Mirando el código, no veo nada raro. Revisa el código que tenías antes y el de ahora para ver diferencias. Este módulo ya no lo uso desde hace bastante, pero estaba funcionando sin problemas con la última actualización.

**Comment by insideth** [comment]
Del módulo project_task_work_print no he variado nada, solo de Odoo y se aplicaron gran cantidad de actualizaciones. ¿Me puedes decir qué fichero/s o vistas tengo que revisar del módulo para ver si ha cambiado algún campo?. A nivel de programación controlo poco. Gracias.

Como comentas que ya no lo usas  ¿Hay otra forma de imprimir los informes de proyectos?

**Comment by pedrobaeza** [comment]
No lo uso porque la versión 8.0 ya es muy antigua y actualicé a versión 9 (y pronto a 10). Tienes que revisar los archivos de la carpeta report.

**Comment by insideth** [comment]
Debe ser algún problema con la conversión de fechas, he modificado la línea 235 del fichero report/taskwork_report.rml:

Inicial: 
`<para style="P2">[[ w.date and formatLang(w.date, date=True) or '' ]]</para>`

Modificada y funcionando (aunque con formato de fecha no español):

`<para style="P2">[[ w.date or '' ]]</para>`
