### ISSUE TITLE
Migration sale_recurring_orders to 10.0 

### ISSUE THREAD

**Issue by javierobcn** [serviciosbaeza/serviciosbaeza-odoo-addons#35]
Hello, i'm interested in migrate sale_recurring_orders to 10.0 , any advice are welcome :)

I have some problem to add in the menu the option "Recurring orders agreements"  ...

`<menuitem name="Recurring orders agreements" id="menu_recurring_orders_agreements" 
            parent="base.menu_sales" action="action_sale_recurring_orders_agreement" 
            sequence="4"/>`

**Comment by pedrobaeza** [comment]
Hi, Javier,

You should ask for general help on Odoo forums.
