### ISSUE TITLE
Report de impuestos con base y cuota

### ISSUE THREAD

**Issue by openmindsystems** [serviciosbaeza/serviciosbaeza-odoo-addons#7]
Hola Pedro, hemos hablado con Albert Cabedo y este report es uno de los que estamos desarrollando nosotros.

Se trata de un informe de impuestos con la base y la cuota separados en columnas diferentes,  

Saludos.

**Comment by pedrobaeza** [comment]
Buenas, me alegra saber de vuestra disposición a colaborar!

Existe ya otro propuesto en la localización https://github.com/OCA/l10n-spain/pull/134 que creo que es parecido.

Mirad a ver si es lo mismo, y coordinar para crear uno conjunto que reúna las necesidades actuales, que son básicamente tener un informe a golpe de un click de lo que legalmente se requiere presentar.

**Comment by openmindsystems** [comment]
Gracias Pedro, lo miramos.

Saludos.
