### ISSUE TITLE
product_category_full_search: duplicate results when both a category and its parent have the searched string in the name

### ISSUE THREAD

**Issue by LeartS** [serviciosbaeza/serviciosbaeza-odoo-addons#9]
### How to reproduce
- Create category Chocolate
- Create category White Chocolate, with parent category Chocolate
- Open a product, go to the internal category field and search for "choco" 
### Result

You get the category "White Chocolate" two times
### Expected Result

The category "White Chocolate" is proposed only one time
### Cause of the bug and how to fix

The category "White chocolate" is added to the ids two times, one because it matches the string "choco" and one because it's a child of the category "Chocolate" which also matches.

The code should use a set to avoid id repetitions

**Comment by pedrobaeza** [comment]
Fixed

Thanks for the report.
